### ISSUE TITLE
Unity 2020.3.14f Import errors

### ISSUE THREAD

**Issue by mkwozniak** [itisnajim/SocketIOUnity#1]
![image](https://user-images.githubusercontent.com/51724102/140596418-2e25b988-1e1e-4781-b64f-b6f2d21692d1.png)

Brand new project, imported from package manager. Any idea how to fix this?

**Comment by itisnajim** [comment]
I see that you are using Nuget to install some packages like System.Text and Newtonsoft-json, just remove/uninstall them from Nuget, SocketIOUnity already comes with these packages

**Comment by mkwozniak** [comment]
That was indeed an issue, and after a while I managed to fix it.

 I had another package (Veggie Studio Pro) which used the Jobs package, which in turn used the unity.com.collections  (System.Runtime.CompilerServices) package. This was creating assembly name conflicts. After updating the Jobs package and manually dragging the DLL's into the Assets folder, all is working. 
Unfortunately I am not able to use the git url with the package manager because of this. Thanks for the response.
