### ISSUE TITLE
Socket.io process keeps running despite Unity editor being stopped.

### ISSUE THREAD

**Issue by DaveKap** [itisnajim/SocketIOUnity#11]
After successfully connecting to a test server with the example client code via the Unity editor in run mode, something peculiar happens after stopping.
![Unity_nZF8C1HejG](https://user-images.githubusercontent.com/2147567/168696910-a1343a30-226a-4905-bd94-e07ed4af1ca8.png)
For some reason the socket.io process just keeps going, despite the fact I stopped the program. I have to kill Unity to make this stop.
I tried to add this code, which should kill the socket when the editor stops, but that doesn't seem to be the case:
```
    private void OnApplicationQuit()
    {
        socket.Disconnect();
    }
```

**Comment by ThimoDEV** [comment]
Have you tried Disconnecting the socket in the OnDisable or OnDestroy method? I don't know if OnApplicationQuit is the best method to use for the editor play mode.
