### ISSUE TITLE
Emit not work on Android and IOS

### ISSUE THREAD

**Issue by dongnhdongnh** [itisnajim/SocketIOUnity#12]
it worked fine on editor but on Android and IOS emit not work

**Comment by vitaliyvorobyov** [comment]
I have the same issue. The library works perfect in Unity Editor, but when ported to the Android device (ARM64) the Emit function doesn't work. Android client is able to connect to the server, but it cannot Emit messages and also no errors are thrown.

**Comment by itisnajim** [comment]
just the Emit? is the receiving good?

try in the play settings -> player -> Other settings -> Configuration to select IL2CPP as a Scripting Backend,
and .NET 4.x as API Compatibility Settings, 

and watch the app debug in the Android Studio or Xcode for more info!

**Comment by vitaliyvorobyov** [comment]
Yeah, the problem is just with the Emit, the receiving works perfectly.

The project is already using IL2CPP, .Net 4.X. Emit still doesn't work on Android device. I've also debugged in the Android Studio and the Emit function is called, but on the server side there is no message. I thought that  maybe the issue is with a server, but when I Emit messages from the Unity Editor server receives them.

**Comment by itisnajim** [comment]
or from the client, maybe you should add some permissions 

like internet for android 
```
<manifest xlmns:android...>
 ...
 <uses-permission android:name="android.permission.INTERNET" />
 <application ...
</manifest>
```
for ios maybe this the prob.. [transport security has blocked-a cleartext http](https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http)

i can't help with no more context or info ...

**Comment by itisnajim** [comment]
maybe related? https://github.com/itisnajim/SocketIOUnity/issues/19

 this will be closed due to inactivity.

**Comment by Kouznetsov** [comment]
I don't think so, the server is working fine. The same thing happens on iOS. Login and message receiving are working but nothing gets emitted. No error is raised either. 
The other thread suggests that android might be missing the internet permission but my game already uses internet without problem. 

It might be related to the fact that my server is not running on https. The thing that's weird is that it still connects and receives messages. I expected everything to fail directly.

**Comment by HungNgo1809** [comment]
The error ""Operation is not supported on this platform. The unsupported member type 'System.Object[]', Path: $."" appears when I call EmitAsync on iOS. It seems that iOS does not support the params object[] type. Is there an alternative solution?

**Comment by itisnajim** [comment]
> The error ""Operation is not supported on this platform. The unsupported member type 'System.Object[]', Path: $."" appears when I call EmitAsync on iOS. It seems that iOS does not support the params object[] type. Is there an alternative solution?

@HungNgo1809 

see the sample file:
https://github.com/itisnajim/SocketIOUnity/blob/main/Samples~/Sample/SocketManager.cs

objects u want to send should be annotated with [System.Serializable]

```cs
    [System.Serializable]
    class TestClass2
    {
        public string text;

        public TestClass2(string text)
        {
            this.text = text;
        }
    }
```

and maybe you want to try this:
```cs
socket.JsonSerializer = new NewtonsoftJsonSerializer();
```

**Comment by HungNgo1809** [comment]
Thank you very much, I was able to resolve the issue by using Socket.EmitStringAsJSON.
