### ISSUE TITLE
Can we get support for socket.io-client-csharp 3.0.6?

### ISSUE THREAD

**Issue by DaveKap** [itisnajim/SocketIOUnity#13]
After getting help from a friend, I discovered that the reason I was having such issues using this plugin's auth methodology was because it's using an older version of socket.io-client-csharp. The newer version, updated in March, allows for authentication middleware support, which I need!
See the fix here:
https://github.com/doghappy/socket.io-client-csharp/issues/266

Would it be possible to update SocketIOUnity to support socket.io-client-csharp 3.0.6?

**Comment by itisnajim** [comment]
i'll do an update tomorrow, and to support more Unity versions too

**Comment by DaveKap** [comment]
Thank you! Looking forward to it!

**Comment by itisnajim** [comment]
you are welcome,
try now https://github.com/itisnajim/SocketIOUnity/releases/tag/v1.1.1

**Comment by DaveKap** [comment]
Thanks! Unfortunately, I got a few warnings and an error upon updating. I tried reinstalling fresh and still got the same errors:
https://i.imgur.com/bOxWcHY.png

**Comment by jingfu-wei** [comment]
Thanks for the amazing update. I also encountered the problem with 

`error CS0103: The name 'Router' does not exist in the current context`

After comparing with version 1.1.0, I found that the folder `Routers` was removed from `Runtime\SocketIOClient`. Was this intentional?

**Comment by jingfu-wei** [comment]
After checking [socket.io-client-csharp](https://github.com/doghappy/socket.io-client-csharp), I have managed to resolve this issue:

- replace `Router` with `_transport` at line 97 in `Runtime\SocketIOUnity.cs`
- `_transport` was set as `private` in `SocketIO` which was defined in `Runtime\SocketIOClient\SocketIO.cs`, so you need to set `_transport ` either `public` or `protected`

This should work. However, I noticed the delay in responsding events sent from the server for some reason. V1.1.0 does not have this problem.

**Comment by itisnajim** [comment]
@jingfu-wei 
please check now, 
i updated this: 
https://github.com/itisnajim/SocketIOUnity/blob/520ea721ce25d2a193ee4c3b50299f617c6d529e/Runtime/SocketIOUnity.cs#L85-L98

i have no way to test it right now, so tell me if i need to modify something ..

**Comment by DaveKap** [comment]
As far as I could tell, implementing the changes jingfu-wei mentioned got things working just as well as they did with commenting out the line altogether. I didn't notice lag in the communications, either.

However, making the change you've shown above cause a new error because cancellationToken is unknown name. Tacking ConfigureAwait(false) onto the end of the unchanged line, however, works fine.
