### ISSUE TITLE
[BUG] V1.1.1 System.Reactive not found import errors

### ISSUE THREAD

**Issue by ThimoDEV** [itisnajim/SocketIOUnity#15]
When I tried to use the latest release (V1.1.1.) I get System.Reactive not found errors.
![bug image](https://user-images.githubusercontent.com/68739517/171593904-a88c2ed3-1ef3-47ea-b2d0-1101f2cd7d07.PNG)

Steps to reproduce:

- Create a new empty unity project
- Import the Socket IO package through git URL add in the package manager.
- System.Reactive not found errors pop up after import.

Tested on:

Unity 2021.3.3 LTS
Unity 2021.2.5

**Comment by binaray** [comment]
I've got this to work by importing in a compiled [System.Reactive.dll](https://github.com/itisnajim/SocketIOUnity/files/8822441/System.Reactive.dll.zip) (attached zip). 
Alternatively, you can compile the source from nuget.

**Comment by itisnajim** [comment]
i updated the git source and added System.Reactive.dll, 
all needed libs now under the folder SocketIOUnity/libs/*
