### ISSUE TITLE
[Question] Reason for socket.JsonSerializer = new NewtonsoftJsonSerializer(); removal in the latest release

### ISSUE THREAD

**Issue by ThimoDEV** [itisnajim/SocketIOUnity#17]
I didn't see NewtonsoftJsonSerializer being removed from the library. Does it now mean it isn't nessesary anymore or was there any other reason for its removal? I think the Readme is now a bit outdated.

**Comment by itisnajim** [comment]
Yes, you are right, I rearrange the packages under Runtime/libs folder, and i forgot to add the Newtonsoft.Json lib...
I have now updated v1.1.2, just remove and re-add the git url to unity package Manager, if everything works you can close this, I'm here if anything needed 😄
