### ISSUE TITLE
Import Errors 

### ISSUE THREAD

**Issue by Sarfraz-droid** [itisnajim/SocketIOUnity#2]
Hi, I was trying to add SocketManager.cs from Samples~ but have been getting these errors.. what could be the possible fix?
Thank You

![image](https://user-images.githubusercontent.com/73013838/141055330-1f2031a0-7dd0-4a8a-b5f3-7fa95101caed.png)

**Comment by itisnajim** [comment]
Which version of Unity are you using?
Try these suggestions:

* Restart Unity and Unity Hub
or
* Create a new (empty) project, in Unity -> Window -> Package Manager -> and click (+) add package from git URL and past: https://github.com/itisnajim/SocketIOUnity.git
Download/Clone this project in a separated folder (away from the new one you created using Unity) 
to download: https://github.com/itisnajim/SocketIOUnity/archive/refs/heads/main.zip
drag and drop from the downloaded folder /Samples\~/Sample to the created project Assets folder,
You will notice that some referenced scripts are missing, to solve: drag SocketManager.cs into Main Camera->Script->Missing (Mono Script) and yea link those Input Fields and objects with the ones exists in the scene.
Add MBlue to Cube (exists in the scene) -> Materials -> Element 0

**Comment by M1ngXU** [comment]
I had the same error, but using the .zip it still has the same errors? any way to fix them?

**Comment by itisnajim** [comment]
I made a video on how to get the simple folder working, using the previous commented instructions: 
https://share.vidyard.com/watch/F7cBZi1jG2mS4mb8AaVJBG?
You may have the first #1 issue, check it too!

**Comment by DuneZerna** [comment]
> Hi, I was trying to add SocketManager.cs from Samples~ but have been getting these errors.. what could be the possible fix? Thank You
> 
> ![image](https://user-images.githubusercontent.com/73013838/141055330-1f2031a0-7dd0-4a8a-b5f3-7fa95101caed.png)

It is a necessity for the import that you have Git installed on your computer. Maybe try that?

**Comment by syedMohib44** [comment]
Having same issue with unity 2020.3.15f2. Does anyone got a fix yet?

**Comment by M1ngXU** [comment]
@syedMohib44 i couldn't get it working. though i did my own one (no ack, no file stuff, just simple sending)

**Comment by syedMohib44** [comment]
@M1ngXU sounds awesome how did you do it can you please help me I have tried many things rn just sending will help alot

**Comment by M1ngXU** [comment]
main part: https://github.com/M1ngXU/Socket.IO-Unity/blob/master/Script/Socket.cs
quite well docummented

**Comment by M1ngXU** [comment]
@syedMohib44 
main part: https://github.com/M1ngXU/Socket.IO-Unity/blob/master/Script/Socket.cs
quite well documented

**Comment by syedMohib44** [comment]
> @syedMohib44 main part: https://github.com/M1ngXU/Socket.IO-Unity/blob/master/Script/Socket.cs quite well documented

Thanks man really appriacte it 👍

**Comment by itisnajim** [comment]
I did an update to support Unity with .Net Standard 2.1 (Unity >= 2021.2.0), I test it with the latest beta Unity 2022.1.0b2 and working fine now, check with yours and please tell me if everything is ok

**Comment by brako** [comment]
I have the same problem with .Net Standard 2.0.

After a little bit of research, System.Memory.dll require those dependencies:
```
System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3
```

But somehow NuGet will download the latest compatible version of them instead:
```
System.Buffers (>= 4.5.1)
System.Numerics.Vectors (>= 4.5.0)
System.Runtime.CompilerServices.Unsafe (>= 4.5.3)
```
More info [here](https://nuget.info/packages/System.Memory/4.5.4)

For example we have the dll System.Runtime.CompilerServices.Unsafe (5.0.0.0) which is different from the required one (4.0.4.1)

You can disable the strong named references in Unity:
In Project **Settings** > **Player** > **Other Settings** > disable **Assembly Version Validation**. ([source](https://docs.unity3d.com/Manual/PluginInspector.html))

I don't know if this is a good option to just ignore this problem. But I'm still stuck after that with a conflict between the Unity package Newtonsoft and the embedded one in SocketIOUnity

@itisnajim I followed exactly what you did in the video but I doesn't work (Unity 2020.3.27f1 LTS)

**Comment by itisnajim** [comment]
All needed libs now under the folder SocketIOUnity/libs/*
