### ISSUE TITLE
Authentication technique

### ISSUE THREAD

**Issue by SincereSuraj** [itisnajim/SocketIOUnity#20]
I want to use Auth mode in socketIOOption to check for authentication token. I could not find any example. i look for solution

**Comment by itisnajim** [comment]
Maybe checking the socket.handshake.auth, instead of the query in the [Server example](https://github.com/itisnajim/SocketIOUnity#server-example) ?

Any things related to socket.io-client-csharp package, you have to post to the main repo:
https://github.com/doghappy/socket.io-client-csharp
