### ISSUE TITLE
Private Rooms

### ISSUE THREAD

**Issue by mohandeep2002** [itisnajim/SocketIOUnity#23]
socket.to(room).emit("event","message") cant send the data to the Unity Client

**Comment by itisnajim** [comment]
try this instead
`io.in(room).emit("event","message")`

**Comment by mohandeep2002** [comment]
Yes Thank you Its working fine now.

**Comment by mohandeep2002** [comment]
When I deploy my server into Heroku, it is not connecting with the Unity Client.
How to resolve this
