### ISSUE TITLE
Doesn't work with socket io servers v3.x.x

### ISSUE THREAD

**Issue by GRyabkin** [itisnajim/SocketIOUnity#24]
Try to change socket io server version to v3.x.x, set EIO in sample to 3

Doesn't work =(

P.S. works fine with v4.2.0

**Comment by itisnajim** [comment]
Change EIO to 4 
And transport to websocket
See:

https://github.com/doghappy/socket.io-client-csharp/blob/master/src/SocketIOClient.Test/SocketIOTests/V3/SocketIOV3Creator.cs


https://github.com/doghappy/socket.io-client-csharp/tree/master/src/socket.io-server-v3

**Comment by GRyabkin** [comment]
> Change EIO to 4 And transport to websocket See:
> 
> https://github.com/doghappy/socket.io-client-csharp/blob/master/src/SocketIOClient.Test/SocketIOTests/V3/SocketIOV3Creator.cs
> 
> https://github.com/doghappy/socket.io-client-csharp/tree/master/src/socket.io-server-v3

yes, it works with v3 with EIO 4 and Websocket as a transport. I curious what the reason to use the wrapper instead of compiled dll of SocketIO .Net library?

**Comment by itisnajim** [comment]
You can use the [main repo](https://github.com/doghappy/socket.io-client-csharp) directly if you want, i've done this wrapper to facilitate & to make it easier to get a running project, working with unity objects, without struggling with the libs, compatibility, errors, and etc..
