### ISSUE TITLE
Nodejs Server is not working in heroku

### ISSUE THREAD

**Issue by mohandeep2002** [itisnajim/SocketIOUnity#25]
I deployed my nodejs server in Heroku. It is connecting with the unity but it is not sending and receiving any data from the server. 

In Unity I used like this for connecting to my server.

`
       var uri = new Uri("ws://herokuapp name<>.herokuapp.com");

        //Creating a socket
        socket = new SocketIOUnity(uri, new SocketIOOptions
        {
            Query = new Dictionary<string, string>
                {
                    {"token", "UNITY" }
                }
            ,
            EIO = 4
            ,
            Transport = SocketIOClient.Transport.TransportProtocol.WebSocket
        });

`

**Comment by meytotr** [comment]
same for glitch.. but i couldnt tell them

**Comment by yeexuanwong** [comment]
Try to change your this portion of code in nodejs from:

`server.listen(port, () => {
  console.log('listening on *:' + port);
});`

to

`server.listen(process.env.PORT || port, () => {
  console.log('listening on *:' + port);
});`

**Comment by itisnajim** [comment]
duplicated: https://github.com/itisnajim/SocketIOUnity/issues/22
