### ISSUE TITLE
Not working with IL2CPP build on android

### ISSUE THREAD

**Issue by Awais6** [itisnajim/SocketIOUnity#26]
It's not working with IL2CPP build on Android, working fine with Mono build, but we can't use Mono because Unity doesn't support Arm64 build with Mono.

**Comment by cheneliezer** [comment]
doesnt work for me on android at all. it connects but cant emit anything

**Comment by itisnajim** [comment]
don't build with Mono, use IL2CPP instead; 
people managed to make it work with Android, always see the older issues to know:
https://github.com/itisnajim/SocketIOUnity/issues/19
https://github.com/itisnajim/SocketIOUnity/issues/16
https://github.com/itisnajim/SocketIOUnity/issues/12
https://github.com/itisnajim/SocketIOUnity/issues/5

**Comment by Pathawut** [comment]
Are there another way to fix this issue without change back to 4.0.0?
because it's working server I can't change it.

**Comment by itisnajim** [comment]
4.2.0 working too

More info please.

**Comment by Pathawut** [comment]
I working on 4.4.0 and It doesn't work on IL2CPP Build.
when I use socket.connect() , It doesn't have any reply message back.
It keep try to attempt reconnect over and over.

**Comment by kimminsu-123** [comment]
had any solutions?

**Comment by Awais6** [comment]
> 

Exactly same happens with me

**Comment by Awais6** [comment]
> had any solutions?

I have moved to the best HTTP 2 asset available on the asset store, working perfectly

**Comment by kimminsu-123** [comment]
> > had any solutions?
> 
> I have moved to the best HTTP 2 asset available on the asset store, working perfectly

https://assetstore.unity.com/packages/tools/network/best-http-2-155981

this link?

**Comment by kimminsu-123** [comment]
Open build settings and replace IL2CPP Code Generation with Fast (smaller) builds. it works

**Comment by Pathawut** [comment]
> Open build settings and replace IL2CPP Code Generation with Fast (smaller) builds. it works

It's work.
Thank you very much.

**Comment by Kouznetsov** [comment]
> Open build settings and replace IL2CPP Code Generation with Fast (smaller) builds. it works

It does, but why?

**Comment by itisnajim** [comment]
> IL2CPP

https://forum.unity.com/threads/il2cpp-build-time-improvements-seeking-feedback.1064135/
