### ISSUE TITLE
Multiple precompiled assemblies with the same name

### ISSUE THREAD

**Issue by gVguy** [itisnajim/SocketIOUnity#28]
Hi! I'm getting this error after I add the package. It seems that Unity includes Newtonsoft.Json.dll by default, and I don't see a way how I can import yours without it.

Here's the full text of the error:

Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included on the current platform. Only one assembly with the same name is allowed per platform. (/...../Library/PackageCache/com.itisnajim.socketiounity@9068aafaf2/Runtime/libs/Newtonsoft.Json Editor/Newtonsoft.Json.dll)

**Comment by gVguy** [comment]
https://github.com/itisnajim/SocketIOUnity/pull/18
This pull request seems to be talking about the same problem

**Comment by CodinSegal** [comment]
it seems that it has came back. Its been two days im trying to fix the error and its seems that i could not make it work

**Comment by RubinGal** [comment]
Hey, I'm facing the same issue, can you please elaborate about your solution?

**Comment by itisnajim** [comment]
> Delete manualy the directory Newtonsoft then add in the dependency "com.unity.nuget.newtonsoft-json": "3.0.2"

no need to delete anything, fixed https://github.com/itisnajim/SocketIOUnity/pull/18
