### ISSUE TITLE
Emit not working on android

### ISSUE THREAD

**Issue by Kouznetsov** [itisnajim/SocketIOUnity#32]
The `socket.Emit()` function works correctly on the Editor. 
My android device receives the messages as expected, but when Emitting from android, nothing shows on the server or elsewhere. The code is the same on the Editor and the Android device.

**Comment by itisnajim** [comment]
duplicated ?
https://github.com/itisnajim/SocketIOUnity/issues/12

**Comment by Kouznetsov** [comment]
I don't think so, the server is working fine. The same thing happens on iOS. Login and message receiving are working but nothing gets emitted. No error is raised either.
The other thread suggests that android might be missing the internet permission but my game already uses internet without problem.

It might be related to the fact that my server is not running on https. The thing that's weird is that it still connects and receives messages. I expected everything to fail directly.

**Comment by itisnajim** [comment]
try these:
https://github.com/doghappy/socket.io-client-csharp/issues/134
https://github.com/doghappy/socket.io-client-csharp/issues/129
https://github.com/doghappy/socket.io-client-csharp/issues/120
https://github.com/doghappy/socket.io-client-csharp/issues/113
https://github.com/doghappy/socket.io-client-csharp/issues/24
https://github.com/doghappy/socket.io-client-csharp/issues/5

and try to emit an empty event, something like:
`socket.Emit("eventName");`

also build on pc/mac and see if this is only on android !?

**Comment by itisnajim** [comment]
try updating unity
see https://github.com/itisnajim/SocketIOUnity/issues/36

**Comment by timbotimbo** [comment]
For me this was caused by IL2CPP breaking the JSON serializer that is used by default.
Simply switching to the Newtonsoft option (that's already included) makes `Emit` work on Android and iOS.

`using SocketIOClient.Newtonsoft.Json;`

```
socket = new SocketIOUnity( ... );
socket.JsonSerializer = new NewtonsoftJsonSerializer();
```

**Comment by wstevenrodriguez** [comment]
> For me this was caused by IL2CPP breaking the JSON serializer that is used by default. Simply switching to the Newtonsoft option (that's already included) makes `Emit` work on Android and iOS.
> 
> `using SocketIOClient.Newtonsoft.Json;`
> 
> ```
> socket = new SocketIOUnity( ... );
> socket.JsonSerializer = new NewtonsoftJsonSerializer();
> ```

it's works thanks

**Comment by jrichardsz** [comment]
> > For me this was caused by IL2CPP breaking the JSON serializer that is used by default. Simply switching to the Newtonsoft option (that's already included) makes `Emit` work on Android and iOS.
> > `using SocketIOClient.Newtonsoft.Json;`
> > ```
> > socket = new SocketIOUnity( ... );
> > socket.JsonSerializer = new NewtonsoftJsonSerializer();
> > ```
> 
> it's works thanks

Would you share us the exact Newtonsoft.Json version?

Thanks
