### ISSUE TITLE
SocketIO can't connect on IOS platform in empty project

### ISSUE THREAD

**Issue by sartubakia** [itisnajim/SocketIOUnity#36]
Can't connect to server in iOS, but other platforms work fine, also android work fine.
<img width="654" alt="Screenshot 2022-11-28 at 13 26 17" src="https://user-images.githubusercontent.com/2877795/204254619-8d6f6ac3-229f-4a6a-961d-b2d2dbd6f895.png">

No any error, attempts to reconnect or other feedback, seems like it crash on other thread in build.

Transport - WebSocket

**Comment by itisnajim** [comment]
try to update unity or use the one before the latest version

**Comment by sartubakia** [comment]
@itisnajim Problem fixed in Unity 2022.1.23) 


Not work in 2021.3.6f1
Testing - 2021.3.14f1

**Comment by jsaade** [comment]
Tried updating Unity and nothing happens on Android. No errors in logs, just no connection. I am not using secure sockets. Works well on Editor.
