### ISSUE TITLE
Issue in unity

### ISSUE THREAD

**Issue by rihno123** [itisnajim/SocketIOUnity#42]
Hi, I have this issue.
![Capture](https://user-images.githubusercontent.com/122835110/212769789-6650da05-7108-4cb6-b078-3ad0c9778347.JPG)
![1](https://user-images.githubusercontent.com/122835110/212769900-4f32a30a-4ab2-4fac-9482-635a8b056513.JPG)

**Comment by itisnajim** [comment]
https://github.com/itisnajim/SocketIOUnity#receiving

**Comment by rihno123** [comment]
> https://github.com/itisnajim/SocketIOUnity#receiving

Can you be more detailed? I don't get it.

**Comment by itisnajim** [comment]
@rihno123, to retrieve your object, it is recommended to use the GetValue<Class> method. For example, to get an object of type 'SomeClass':
```cs
var obj = response.GetValue<SomeClass>();
```
If the object is a string, you can use:
```cs
string text = response.GetValue<string>();
```
Alternatively, if you wish to view the object as a stringified JSON, you can use:
```cs
string jsonStr = response.GetValue(0).GetRawText();
```

**Comment by rihno123** [comment]
> @rihno123, to retrieve your object, it is recommended to use the GetValue method. For example, to get an object of type 'SomeClass':
> 
> ```cs
> var obj = response.GetValue<SomeClass>();
> ```
> 
> If the object is a string, you can use:
> 
> ```cs
> string text = response.GetValue<string>();
> ```
> 
> Alternatively, if you wish to view the object as a stringified JSON, you can use:
> 
> ```cs
> string jsonStr = response.GetValue(0).GetRawText();
> ```

Ok, but when I use that line I get this error.
![Capture](https://user-images.githubusercontent.com/122835110/214695217-00b2c8dd-fac7-499c-b042-620d1f20e69e.JPG)

**Comment by SatoshiDark** [comment]
Hi, I have the same issue as the first screenshot, I'm at Unity version 2021.3.17f1.
I imported the package without issues, but when I copied the sample folder then the unity console log shows that error.
As I'm just testing this package for the GGJ, I replaced the error line `response.GetValue().GetRawText()` with `response.ToString()` and seems to work, but I'll really appreciated if you can update the sample directory please.
