### ISSUE TITLE
Can't import package and manual "import" results in errors

### ISSUE THREAD

**Issue by Kyliathy** [itisnajim/SocketIOUnity#49]
Hi there :). Thank you for creating this library! Having lots of issues with socket-io assets for Unity, been struggling for over a week due to WebSocketSharp not playing nice with socket.io v4.

I've added this package successfully, but the code files aren't actually added to the project. So I can't actually use anything. So, I manually copied the files into Assets, but then I get tons of errors unless I also import the "libs" folder. But then further down the rabbit hole I go, because once I import the "libs" folder, I get duplicated assembly errors. And if I try to delete the package from PackageCache, nothing works anymore :(. Any suggestions are welcome! I'm on Unity 2021.3 BTW.

**Comment by itisnajim** [comment]
try installing from the url in a new empty project

**Comment by mihaibrana** [comment]
I did. And it worked. And then I switched back to my project. And for whatever reason I don't understand, that one worked too :). And I managed to connect to the server I wanted. THANK YOU! :)

**Comment by Kyliathy** [comment]
I did. And it worked. And then I switched back to my project. And for whatever reason I don't understand, that one worked too :). And I managed to connect to the server I wanted. THANK YOU! :)
