### ISSUE TITLE
WSS support

### ISSUE THREAD

**Issue by popkingcorn** [itisnajim/SocketIOUnity#50]
Does this library supports wss?
With WS all works great, but with wss i can't connect to server.

**Comment by itisnajim** [comment]
you can set the Transport propoerty to SocketIOClient.Transport.TransportProtocol.WebSocket

```cs
var uri = new Uri("https://www.example.com");
socket = new SocketIOUnity(uri, new SocketIOOptions
{
    Query = new Dictionary<string, string>
        {
            {"token", "UNITY" }
        }
    ,
    Transport = SocketIOClient.Transport.TransportProtocol.WebSocket
});
```

otherwise check with the original repo 
https://github.com/doghappy/socket.io-client-csharp
