### ISSUE TITLE
Not connecting to remote server!

### ISSUE THREAD

**Issue by Abdallah-Alwarawreh** [itisnajim/SocketIOUnity#51]
when i connect to localhost with unity it works fine, but when I upload it to my remote server it doesn't work it returns unable to connect to remote server, but when I try to connect with this site "http://amritb.github.io/socketio-client-tool/", it works just fine

### app.ts:
```
import { SocketServer } from "./Classes/Server";
import { WebServer } from "./Web/WebServer";
import express, { Express, Request, Response } from 'express';
const PORT = process.env.PORT || 8080;
// const PORT = 8080;

const http = require('http');
const app: Express = express();
const server = http.createServer(app);

var GameServer = new SocketServer(server);
var AdminServer = new WebServer(app);

server.listen(PORT, () => {
    console.log(`Server listening on port ${PORT}`);
});
```

### server.ts
```
constructor(server: http.Server) {
        this.io = new Server(server, {
            cors: {
                origin: "*"
            }
        });
        
        this.DatabaseHandler = new DatabaseHandler();
        this.Connections = [];
        this.Lobbies = [];

        this.io.use(async (socket: Socket, next: any) => {
            console.log("Hit!");
            .......
        });
}
```

**Comment by Abdallah-Alwarawreh** [comment]
2021.3.19f1, unity editor on windows (android platform), the log just says `unable to connect to remote server`

```
socket = new SocketIOUnity(uri, new SocketIOOptions {
    Query = new Dictionary<string, string>
		{
			{"id", EncryptedId},
			{"username", EncryptedUsername},
			{"avatarURL", EncryptedAvatarURL},
		}
	,
	EIO = 4,
	Transport = SocketIOClient.Transport.TransportProtocol.WebSocket,
});
```

**Comment by farmme-quannv** [comment]
Hi, I got same issue but on Windows builds, socket called connect but no response from socket about OnConnected/OnError/...

**Comment by Abdallah-Alwarawreh** [comment]
> make sure the internet permission is enabled in the manifest (maybe its the cause)
> 
> ```
> <manifest xlmns:android...>
>  ...
>  <uses-permission android:name="android.permission.INTERNET" />
>  <application ...> ... </application>
> </manifest>
> ```
> 
> do the things in this comment: [#45 (comment)](https://github.com/itisnajim/SocketIOUnity/issues/45#issuecomment-1432943813) try this if fixed ur problem.

I'm testing in unity editor, it it doesn't work, but it is working on localhost, just the remote server that is not working

**Comment by Abdallah-Alwarawreh** [comment]
Btw this is my package.json
```json
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "run": "node dist/app.js",
    "build": "tsc -p tsconfig.json"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "crypto": "^1.0.1",
    "ejs": "^3.1.8",
    "express": "^4.18.2",
    "mysql": "^2.18.1",
    "nodemon": "^2.0.20",
    "socket.io": "^4.5.4",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@types/express": "^4.17.15",
    "@types/mysql": "^2.15.21",
    "@types/node": "^18.11.18",
    "@types/socket.io": "^3.0.2",
    "tsc": "^2.0.4"
  }
}
```

**Comment by Abdallah-Alwarawreh** [comment]
Hi, i stopped it from reconnecting only connecting and I don't get anything back no OnConnected or OnError

**Comment by Abdallah-Alwarawreh** [comment]
Fixed the issue!

just changed to port from 80 to 3001 and it worked!
