### ISSUE TITLE
can not find a reference to assembly 'System.Memory'

### ISSUE THREAD

**Issue by mrbaz1997** [itisnajim/SocketIOUnity#52]
<img width="584" alt="screen" src="https://user-images.githubusercontent.com/33225175/230732400-3093918b-6230-4fad-9b30-fce7af31ab0a.png">
your package include **'System.Memory'**  but raise errors relate to _can not find a reference to assembly 'System.Memory'_, I have no idea how to fix it. can anyone help me please.

Windows 11
unity 2020.3.46f1

**Comment by itisnajim** [comment]
close and reopen unity, sometimes this happen.

**Comment by mrbaz1997** [comment]
I think Unity 2020.3.46 and older version editor doesn't support some dll
in Unity 2021.3 has no error
