### ISSUE TITLE
emitWithAck missing

### ISSUE THREAD

**Issue by thephox1982** [itisnajim/SocketIOUnity#66]
I spent a little bit looking into the methods internally here and found a really nice feature seems to be missing or perhaps I am not seeing where/how it is implemented which is emitWithAck.

emitWithAck allows to send data to the server and then get back data as a promise. I REALLY could use this part of socket.io in my Unity project as right now I am having to resort to callback hell in order to pull off what I'm needing done.

Thanks for the help or consideration!

**Comment by thephox1982** [comment]
```
await socket.EmitAsync("getMD5", response => {
  string text = response.GetValue<string>();
  JSONObject jsonObject = new JSONObject(text);
      
  return jsonObject["data"]["test"].stringValue;
}, theData);
```

This is so close to being perfect, but the return from EmitAsync is void so it doesn't allow for passing the result back to the containing method, and I can't assign to a variable outside response function as despite EmitAsync being async, me trying to use the value after the EmitAsync results in empty variable (see below).

```
string res = "";
await socket.EmitAsync("getMD5", response => {
  string text = response.GetValue<string>();
  JSONObject jsonObject = new JSONObject(text);
      
  res = jsonObject["data"]["test"].stringValue;
}, theData);

Debug.Log(res); <== This is empty.
```

I might just change the source for EmitAsync to allow for a return type that is not void which should result in what I need to accomplish but still would be nice feature to not have to go in and modify the source.

Cheers!

**Comment by itisnajim** [comment]
use `TaskCompletionSource`:

```csharp
using System.Threading.Tasks;

public class YourClass
{
    public async Task<string> GetResultAsync()
    {
        var tcs = new TaskCompletionSource<string>();

        await socket.EmitAsync("getMD5", response =>
        {
            string text = response.GetValue<string>();
            JSONObject jsonObject = new JSONObject(text);
            string res = jsonObject["data"]["test"].stringValue;

            tcs.SetResult(res);
        }, theData);

        return await tcs.Task;
    }
}
```

or this is better in term of performance
```csharp

public async ValueTask<string> GetResultAsync()
    {
        var tcs = new TaskCompletionSource<string>();

        await socket.EmitAsync("getMD5", response =>
        {
            string text = response.GetValue<string>();
            JSONObject jsonObject = new JSONObject(text);
            string res = jsonObject["data"]["test"].stringValue;

            tcs.SetResult(res);
        }, theData);

        return await tcs.Task;
    }
```

usage:

```csharp
public async Task UseGetResultAsync()
{
    YourClass instance = new YourClass();
    string result = await instance.GetResultAsync();
    // Use the 'result' here, it will contain the value from the callback.
    Debug.Log(result);
}
```

if not working check with @doghappy at: https://github.com/doghappy/socket.io-client-csharp

**Comment by thephox1982** [comment]
Hey, I was able to get what I needed in another fashion but this is looking mighty handy, I will do some unit testing probably tomorrow and try it out and get back here on how that goes, this could prove useful in the future for sure, thanks!

**Comment by thephox1982** [comment]
Forgot to close..
