### ISSUE TITLE
Errors on import

### ISSUE THREAD

**Issue by Mou1z** [itisnajim/SocketIOUnity#67]
I used this package without any problems on a different device with a slightly older version of Unity. However I just recently created a new empty project and when I import this package I get a bunch of these errors:

```
Library\PackageCache\com.itisnajim.socketiounity@c9e06b1539\Runtime\SocketIOClient\JsonSerializer\ByteArrayConverter.cs(47,13): error CS0012: The type 'ReadOnlySpan<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

**Comment by itisnajim** [comment]
have you tried closing and reopening unity?
if that not work.. try to import manually the [`System.Memory.dll`](https://github.com/itisnajim/SocketIOUnity/blob/main/Runtime/libs/System.Memory.dll) into your assets folder (by drag and drop)

**Comment by Mou1z** [comment]
I was using the Unity version 3.24, I just updated it to the latest and it works now, thanks.
