### ISSUE TITLE
Won't connect to port 80

### ISSUE THREAD

**Issue by Abdallah-Alwarawreh** [itisnajim/SocketIOUnity#68]
im using plesk to host my game server, using normal socket.io on the web works fine, but when i ported my game to unity it worked fine in the localhost because it was on port 3000, when i moved the server to plesk on port 80 it stopped connecting, i changed the port on plesk to 3000 and it worked just fine, but plesk doesn't like me opening ports so im stuck with port 80

Windows Unity 2021.3.19f1
Nodejs Socket.io latest

Im listening on the correct port and exposing the server with "0.0.0.0"

**Comment by itisnajim** [comment]
So it has nothing to do with this package, right?
