### ISSUE TITLE
 error CS0012: The type 'ReadOnlyMemory<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

### ISSUE THREAD

**Issue by sunlighing** [itisnajim/SocketIOUnity#69]
when i import this package ,but have follows error

**Comment by sunlighing** [comment]
![image](https://github.com/itisnajim/SocketIOUnity/assets/22463492/e14b6448-db61-4ea3-aeaa-8dac9e01afd4)

**Comment by sunlighing** [comment]
unity version 2020.3.39 ,socketio 1.14

**Comment by strobert22** [comment]
Hi @sunlighing 

im using unity 2020.3.46f1
same problem here. 

(disclaimer: i dont know what im doing)
im try adding "System.Memory.dll" on file itisnajim.SocketIOUnity.asmdef  

like this
`{
    "name": "SocketIOUnityAssembly",
    "rootNamespace": "",
    "references": [],
    "includePlatforms": [],
    "excludePlatforms": [],
    "allowUnsafeCode": false,
    "overrideReferences": true,
    "precompiledReferences": [
        "Microsoft.Bcl.AsyncInterfaces.dll",
        "Newtonsoft.Json.dll",
        "System.Reactive.dll",
        "System.Memory.dll",
        "System.Runtime.CompilerServices.Unsafe.dll",
        "System.Text.Json.dll",
        "System.Text.Encodings.Web.dll"
    ],
    "autoReferenced": true,
    "defineConstraints": [],
    "versionDefines": [],
    "noEngineReferences": false
}`
then 
Go to Project View, right-click on foldier Packages/Unity SockerIO and press "reimport"

now I don't have any errors and everything seems to compile fine but when I try to use the SocketUIClient I get it that the namespace dont exist.

im keep trying.

**Comment by TiagoAndreAlmeida** [comment]
Any update on this ?

**Comment by LabGuy94** [comment]
Having the same issue on 2019.4.39f

**Comment by Thomasdfoz** [comment]
To fix the error, just edit itisnajim.SocketIOUnity.asmdef and add this library

{
    "name": "SocketIOUnityAssembly",
    "rootNamespace": "",
    "references": [],
    "includePlatforms": [],
    "excludePlatforms": [],
    "allowUnsafeCode": false,
    "overrideReferences": true,
    "precompiledReferences": [
        "Microsoft.Bcl.AsyncInterfaces.dll",
        "Newtonsoft.Json.dll",
        "System.Reactive.dll",
        "System.Runtime.CompilerServices.Unsafe.dll",
        "System.Text.Json.dll",
        "System.Text.Encodings.Web.dll",
	"System.Memory.dll"

    ],
    "autoReferenced": true,
    "defineConstraints": [],
    "versionDefines": [],
    "noEngineReferences": false
}
