### ISSUE TITLE
IL2CPP Android connection issue

### ISSUE THREAD

**Issue by AtulAbhiwan03** [itisnajim/SocketIOUnity#70]
Not connecting with il2cpp unity android

**Comment by itisnajim** [comment]
duplicated:

in device (or in a release mode) you have to add internet permission to your android app mainfest
```xml
<manifest xlmns:android...>
 ...
 <uses-permission android:name="android.permission.INTERNET" />
 <application ...> ... </application>
</manifest>
```

don't use port 80 for you server socket ...

see:
https://github.com/itisnajim/SocketIOUnity/issues/51
