### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by ScottasM** [itisnajim/SocketIOUnity#73]
In editor it's absolutely fine - everything works perfectly. But when i export it on android nothing happens, the adb logcat doesnt show any errors/warnings/messages related to socketio, just nothing happens.
Im exporting with il2cpp, ARMv7 disabled, arm64 enabled, internet settings set to required. Unity version - 2021.3.8f1 (maybe it's too old?)

**Comment by ScottasM** [comment]
Updated the version to 2022.3.10f1, still the same.

**Comment by ScottasM** [comment]
also im building with il2cpp if that matters.

**Comment by ScottasM** [comment]
One more thing to note - the android app seems to be reaching my flask socketio server, because it keeps spamming post requests every few seconds (probably trying to reconnect) but the sockets arent established

**Comment by ScottasM** [comment]
Okay, after 4 days of this torture i fixed it. 
for any other lost souls out there here what was wrong : 
Apparently android didnt trust my ssl certificate, and didnt print anything to logcat, so when i added all the events like OnReconnectFail, OnRecconectAttempt and etc. i finally saw the error.

what i had to do was : 
cat certificate.crt ca_bundle.crt > chained.pem to generate the chained.pem file for android to trust 

and then in my flask socketio app i changed the path to point from certificate.crt to chained.pem

**Comment by rehan303** [comment]
> Okay, after 4 days of this torture i fixed it. for any other lost souls out there here what was wrong : Apparently android didnt trust my ssl certificate, and didnt print anything to logcat, so when i added all the events like OnReconnectFail, OnRecconectAttempt and etc. i finally saw the error.
> 
> what i had to do was : cat certificate.crt ca_bundle.crt > chained.pem to generate the chained.pem file for android to trust
> 
> and then in my flask socketio app i changed the path to point from certificate.crt to chained.pem

Hi, I have been facing same issue on android.

Kindly help how did you resolve it.


Thanks

**Comment by ScottasM** [comment]
> > Okay, after 4 days of this torture i fixed it. for any other lost souls out there here what was wrong : Apparently android didnt trust my ssl certificate, and didnt print anything to logcat, so when i added all the events like OnReconnectFail, OnRecconectAttempt and etc. i finally saw the error.
> > what i had to do was : cat certificate.crt ca_bundle.crt > chained.pem to generate the chained.pem file for android to trust
> > and then in my flask socketio app i changed the path to point from certificate.crt to chained.pem
> 
> Hi, I have been facing same issue on android.
> 
> Kindly help how did you resolve it.
> 
> Thanks

what do you mean? I explained how i fixed it

**Comment by BorisMolch** [comment]
> > > Okay, after 4 days of this torture i fixed it. for any other lost souls out there here what was wrong : Apparently android didnt trust my ssl certificate, and didnt print anything to logcat, so when i added all the events like OnReconnectFail, OnRecconectAttempt and etc. i finally saw the error.
> > > what i had to do was : cat certificate.crt ca_bundle.crt > chained.pem to generate the chained.pem file for android to trust
> > > and then in my flask socketio app i changed the path to point from certificate.crt to chained.pem
> > 
> > 
> > Hi, I have been facing same issue on android.
> > Kindly help how did you resolve it.
> > Thanks
> 
> what do you mean? I explained how i fixed it

so the issue was on server side? not client?
its not related to https://github.com/itisnajim/SocketIOUnity/issues/75 ?

**Comment by ScottasM** [comment]
> > > > Okay, after 4 days of this torture i fixed it. for any other lost souls out there here what was wrong : Apparently android didnt trust my ssl certificate, and didnt print anything to logcat, so when i added all the events like OnReconnectFail, OnRecconectAttempt and etc. i finally saw the error.
> > > > what i had to do was : cat certificate.crt ca_bundle.crt > chained.pem to generate the chained.pem file for android to trust
> > > > and then in my flask socketio app i changed the path to point from certificate.crt to chained.pem
> > > 
> > > 
> > > Hi, I have been facing same issue on android.
> > > Kindly help how did you resolve it.
> > > Thanks
> > 
> > 
> > what do you mean? I explained how i fixed it
> 
> so the issue was on server side? not client? its not related to #75 ?

Yeah, it was. Unfortunately the logs didnt show it earlier, so had to torture myself for a few days.
