### ISSUE TITLE
SocketIOResponse could not be found

### ISSUE THREAD

**Issue by frostfire1** [itisnajim/SocketIOUnity#76]
I try to get json response using SocketIOResponse but unity can't find it

error CS0246: The type or namespace name 'SocketIOResponse' could not be found (are you missing a using directive or an assembly reference?)
`socket.On("updatePlayerMovement", (SocketIOResponse response) =>
        {
            UpdateOtherPlayerMovement(response);
        });`

**Comment by itisnajim** [comment]
omit the type for now, and for UpdateOtherPlayerMovement args use directly the values needed instead of the whole response, e.g: 
```csharp
socket.On("updatePlayerMovement", (response) =>
{
    var playerPosition = response.GetValue<PlayerPosition>();
    UpdateOtherPlayerMovement(playerPosition)
});
```

**Comment by frostfire1** [comment]
okay its work
