### ISSUE TITLE
Error in webGL Build - Unable to connect socket

### ISSUE THREAD

**Issue by arunandroapps** [itisnajim/SocketIOUnity#87]
NotSupportedException: C:/Program Files/Unity/Hub/Editor/2023.2.17f1/Editor/Data/il2cpp/libil2cpp/icalls/System/System.Diagnostics/Process.cpp(47) : Unsupported internal call for IL2CPP:NativeMethods::GetProcessData - "IL2CPP does not support access to process data"

**Comment by itisnajim** [comment]
Web not supported, u can combine this package with another one that support web, search in issues of how to do that.
