### ISSUE TITLE
Adding Volatile Emission

### ISSUE THREAD

**Issue by Mathiaszero** [itisnajim/SocketIOUnity#88]
In the JS library there is way to emit volatile. I think your project does not have a wrapper for that, and was wondering if it could be added. I could use it for projectile, fast movement, and other parts of my game where I can sacrifice reliability for reduce overhead. See also https://socket.io/docs/v4/emitting-events/#volatile-events

**Comment by itisnajim** [comment]
Please this way: https://github.com/doghappy/socket.io-client-csharp/issues
SocketIOUnity its just a wrapper for socket.io-client-csharp
