### ISSUE TITLE
Lots of Errors appeared as soon as I installed the package

### ISSUE THREAD

**Issue by JoyX2** [itisnajim/SocketIOUnity#9]
![image](https://user-images.githubusercontent.com/101886922/166495364-96744371-030e-44d6-afaf-336f2ca293fc.png)

Restarting doesn't help and this is a new project
I'm using unity 2019.4.36f1

![image](https://user-images.githubusercontent.com/101886922/166496938-392b36f8-8fd4-4687-ad2c-7b5a2f98f212.png)

I've tried to do the same as you mentioned here 
https://share.vidyard.com/watch/F7cBZi1jG2mS4mb8AaVJBG
but it got worth
I got extra four errors

![image](https://user-images.githubusercontent.com/101886922/166500203-79d0604c-3cc8-4325-a30a-b1892a4d2ded.png)

how to fix this ?

**Comment by itisnajim** [comment]
try this url instead to install (with the #v1.0.0 suffix)
https://github.com/itisnajim/SocketIOUnity.git#v1.0.0

**Comment by Gabriele2991** [comment]
@itisnajim I'm trying to run the newer version of your SocketIOUnity with unity v 2021.3.1f and have the same errors that show up in @JoyX2 screenshots.

(Library\PackageCache\com.itisnajim.socketiounity@5106ed6444\Runtime\SocketIOClient.Newtonsoft.Json\NewtonsoftJsonSerializer.cs(64,21): error CS0246: The type or namespace name 'JsonSerializerSettings' could not be found (are you missing a using directive or an assembly reference?)

 BTW the previous version works really fine for me(thank you for your hard work) but i really need to make it run on the newer unity version. Do you have any tips?

**Comment by Feelixe-tin** [comment]
I get the same errors in Unity 2021.3.1f1

**Comment by itisnajim** [comment]
All needed libs now under the folder SocketIOUnity/libs/*
